### ISSUE TITLE
55-70 Sharna Speeds Differ From LvL 55-70 Class Polymorphs

### ISSUE THREAD

**Issue by kevinsane** [l1j/en#344]
Level 55-70 polymorphs are already broken by not increasing in speed as you increase the level of polymorph, but lvl 55-70 sharna scrolls do so someone using level 70 sharna has a large advantage in swing speed and walk speed. I hope the regular polymorphs are fixed soon. :)

**Comment by stanisdead** [comment]
I have noticed a slight difference as well. I just didn't want to say anything yet without further research. Thank you for the post!

**Comment by stanisdead** [comment]
I found after researching more that the walk and casting speeds seem the same between the 55+ Sharna and 55+ Polymorphs but the swing (attack) speed is actually slower using the Sharna scrolls. I don't know if it is because of my class/wep but I didn't think that mattered. I am a Mage using a staff. I switched between 60+ DK and 60+ Sharna, and the DK had a noticeably greater swing speed. I used 30 second intervals to test each the swing and cast speed of both, and the only difference I was able to notice was that swing was greater using Polymorphs.

**Comment by kevinsane** [comment]
For a Knight and DE 70 sharna is faster in both walk and swing. From what
I've found.

**Comment by Soren8** [comment]
Swing speed for a single polymorph does vary with weapon type. However, all polymorph speeds are hard coded in the client, so we can't do anything about it.

**Comment by stanisdead** [comment]
Thank you Soren!

**Comment by everial** [comment]
> However, all polymorph speeds are hard coded in the client, so we can't do anything about it.

This isn't (or at least wasn't) always true - you could unpack certain files, fiddle with frame data, and then have customized speeds.

A server could decide to distribute custom files with different speeds for each of the various polymorphs if you want them all to have distinct cast/walk/attack speeds.

Since unapproved modifications are one way of speed hacking, you probably want to turn on AcceleratorChecker if you're playing with polymorph speeds.
